title: Creative Reflective Journal
email: pmiguelfs@gmail.com
description: >-
  I develop games that never get published. Currently studying Indie Game Development at Falmouth University.
#baseurl: "" 
url: "https://pedr0silva.github.io/"
twitter_username: 
github_username:  pedr0silva


# Build settings
defaults:
  - scope:
      path: "assets/img"
    values:
      image: true

theme: jekyll-theme-console

plugins:
  - jekyll-feed

header_pages:
  - index.md
  - about.md

style: dark # dark (default), light or hacker

#footer: 'follow us on <a href="https://twitter.com/xxx">twitter</a>'